name: Docker Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Latest BYOND version.txt
        run: wget https://secure.byond.com/download/version.txt

      - name: Set BYOND_VERSION
        run: echo `BYOND_VERSION=$(cat version.txt | awk '{$1=$1};1')` >> $GITHUB_ENV

      - name: Set BYOND_MAJOR
        run: echo `BYOND_MAJOR=$(cut -d'.' -f1 <<< $BYOND_VERSION)` >> $GITHUB_ENV

      - name: Set BYOND_MINOR
        run: echo `BYOND_MINOR-$(cut -d'.' -f2 <<< $BYOND_VERSION)` >> $GITHUB_ENV

      - name: Build and Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dameonowen/byond
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}
          dockerfile: Dockerfile
          buildargs: BYOND_MAJOR,BYOND_MINOR
          tags: "latest,${{ env.BYOND_VERSION }}"
          cache: true
          registry: ghcr.io
